name: ORAS Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Install ORAS CLI
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v0.12.0/oras_0.12.0_linux_amd64.tar.gz
          mkdir -p oras-install/
          tar -zxf oras_0.12.0_*.tar.gz -C oras-install/
          mv oras-install/oras /usr/local/bin/
          rm -rf oras_0.12.0_*.tar.gz oras-install/
      - name: Test ORAS CLI installation
        run: |
          oras --help
          oras help login
          oras help logout
          oras help pull 
          oras help push
      - name: Create and artifact to upload
        run: |
          echo "prueba de contenido" >> artefacto.txt
          zip -q artefacto.zip artefacto.txt
      - name: Login to the ghcr
        run: |
          oras login -p $GITHUB_TOKEN ghcr.io
      - name: Push the artifact
        run: |
          oras push ghcr.io/${{ github.repository_owner }}/artefacto:latest artefacto.zip
